#ifndef CADMIUM_EDITOR_COMPONENT_INSPECTOR
#define CADMIUM_EDITOR_COMPONENT_INSPECTOR
#include <cadmium/assets/asset_types.hpp>
#include <cadmium/ecs/world.hpp>
#include <cadmium/editor/component_commands.hpp>
#include <cadmium/editor/component_edit_command.hpp>
#include <cadmium/editor/undo_stack.hpp>
#include <any>
#include <functional>
#include <memory>
#include <vector>
#include <string>

#ifdef CADMIUM_IMGUI
#include <imgui.h>
#endif

namespace Cadmium::Editor
{
  // Transform is present on every editor-created entity; matched by name so
  // InspectorPanel can identify it without knowing the concrete type.
  inline constexpr const char* k_AlwaysPresentComponentName = "Transform";
  inline bool IsAlwaysPresentComponent(const std::string& name) { return name == k_AlwaysPresentComponentName; }

  struct ComponentInspectorEntry
  {
    std::string name;
    std::function<bool(World&, Entity)> has;
    std::function<void(World&, Entity)> draw;

    // Optional: called when an asset is dropped on this component's header.
    // Only useful for components with an asset-backed field.
    std::function<void(World&, Entity, const std::string& assetPath, AssetType)> onAssetDropped;

    // Auto-generated by Register<T>: add/remove via undo stack.
    std::function<void(World&, Entity)> addDefault;
    std::function<void(World&, Entity)> remove;

    // Auto-generated by Register<T>: type-erased copy/restore for
    // WorldSnapshotService across Play/Stop.
    std::function<std::any(World&, Entity)> snapshot;
    std::function<void(World&, Entity, const std::any&)> restore;
  };

  class ComponentInspector
  {
  public:
    static ComponentInspector& Get() { static ComponentInspector i; return i; }

    // T must be copyable and default-constructible.
    // draw() is wrapped with undo/redo tracking: edits become a single undo
    // step when a widget drag ends, and add/remove/snapshot are wired to
    // the undo stack and WorldSnapshotService.
    template<typename T>
    void Register(std::string name, std::function<void(T&)> draw,
                  std::function<void(World&, Entity, const std::string&, AssetType)> onAssetDropped = nullptr)
    {
      auto editState = std::make_shared<EditTrackingState<T>>();
      std::string componentName = name;

      auto wrappedDraw = [draw, editState, componentName](World& w, Entity e)
      {
        T& component = w.GetComponent<T>(e);

        // Drop stale in-progress snapshot if selected entity changed.
        if (editState->entity != e)
        {
          editState->editing = false;
          editState->entity = e;
        }

#ifdef CADMIUM_IMGUI
        bool activeBefore = ImGui::IsAnyItemActive();

        if (!editState->editing)
          editState->snapshot = component;

        draw(component);

        bool activeAfter = ImGui::IsAnyItemActive();

        if (activeAfter)
        {
          editState->editing = true;
        }
        else if (editState->editing)
        {
          editState->editing = false;
          UndoStack::Get().Push(std::make_unique<ComponentEditCommand<T>>(
              w, e, componentName, editState->snapshot, component));
          // Not calling ExecuteAndPush(): the widget already modifies the values.
        }
#else
        draw(component);
#endif
      };

      m_Entries.push_back({
        name,
        [](World& w, Entity e) { return w.HasComponent<T>(e); },
        wrappedDraw,
        std::move(onAssetDropped),
        [componentName](World& w, Entity e)
        {
          UndoStack::Get().ExecuteAndPush(std::make_unique<AddComponentCommand<T>>(w, e, componentName));
        },
        [componentName](World& w, Entity e)
        {
          UndoStack::Get().ExecuteAndPush(std::make_unique<RemoveComponentCommand<T>>(w, e, componentName));
        },
        [](World& w, Entity e) -> std::any
        {
          return w.GetComponent<T>(e);
        },
        [](World& w, Entity e, const std::any& value)
        {
          // AddComponent, not assign: restore runs on a freshly recreated entity.
          w.AddComponent<T>(e, std::any_cast<T>(value));
        }
      });
    }

    const std::vector<ComponentInspectorEntry>& Entries() const { return m_Entries; }

  private:
    template<typename T>
    struct EditTrackingState
    {
      bool   editing = false;
      Entity entity  = k_NullEntity;
      T      snapshot{};
    };

    std::vector<ComponentInspectorEntry> m_Entries;
  };

} // namespace Cadmium::Editor
#endif // CADMIUM_EDITOR_COMPONENT_INSPECTOR
